" Create autoload for 'plugged'
if empty(glob('~/.vim-plugged/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
" vim-plug plugin manager
call plug#begin('~/.vim-plugged/autoload/plugged')
"JellyBean Colorscheme
Plug 'git@github.com:fvalenziano/jellybeans.vim.git'
" Docker syntax
Plug 'git@github.com:fvalenziano/Dockerfile.vim.git'
" vimwiki
Plug 'git@github.com:fvalenziano/vimwiki.git'
" calendar-vim (for vimwiki)
Plug 'git@github.com:fvalenziano/calendar-vim.git'
" end plugins
call plug#end()

set number
set ai " enable auto-indent

"Formatting
" tabs are read as 4 spaces, tabs become spaces
set tabstop=8
set expandtab
set softtabstop=4
colorscheme jellybeans
set cursorline " underlines cursor location
set nowrap " disable wordwrap

" Navigation
" perform menu navigation, but not autocompletion
set wildmenu
set wildmode=longest:full,full
" split navigation shortcuts
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
" Open the new split pane on bottom/right
set splitbelow
set splitright
" Insert new line without entering insert mode
" and without jumping to new line
" GVim version of 'new line above current position'
nmap <S-Enter> O<Esc>j
" Console version of 'new line above current position'
nmap <C-o> O<Esc>j
" insert new line below current position
nmap <CR> o<Esc>k

" vimwiki requirements
set nocompatible
filetype plugin on
syntax on
" vimwiki settings
let g:vimwiki_list = [{'path': '~/Dropbox/private/vimwiki/index.wiki', 'syntax': 'markdown', 'ext': '.md'}]
au BufRead,BufNewFile *.wiki set filetype=vimwiki
function! ToggleCalendar()
  execute ":Calendar"
  if exists("g:calendar_open")
    if g:calendar_open == 1
      execute "q"
      unlet g:calendar_open
    else
      g:calendar_open = 1
    end
  else
    let g:calendar_open = 1
  end
endfunction
:autocmd FileType vimwiki map c :call ToggleCalendar()

" auto-persist folds
augroup AutoSaveFolds
    autocmd!
    autocmd BufWinLeave,BufLeave,BufWritePost ?* nested silent! mkview!
    autocmd BufWinEnter ?* silent! loadview
augroup END
