FROM alpine:latest
LABEL maintainer "frank@valenziano.us"
ENV LANG C.UTF-8

RUN apk --no-cache update && \
            apk --no-cache upgrade && \
            apk add --no-cache \

ENTRYPOINT [ "/bin/sh" ]
